name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1

    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment-dev.yml

    - name: Install xcanvas
      run: |
        mkdir build
        cd build
        cmake .. \
          -D CMAKE_PREFIX_PATH=$CONDA_PREFIX \
          -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
          -D CMAKE_INSTALL_LIBDIR=lib \
          -D CMAKE_C_COMPILER=$CC \
          -D CMAKE_CXX_COMPILER=$CXX
        make install -j ${{ steps.cpu-cores.outputs.count }}

    - name: Run tests
      run: pytest .
